apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: futakai-cert
  namespace: istio-system
spec:
  secretName: futakai-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - futakai.com
