apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-cert
  namespace: istio-system
spec:
  secretName: cloudflare-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
      - jenkins.sujangcloud.uk
      - leakedgyals.com
      - vault.sujangcloud.uk
      - kiali.sujangcloud.uk
